DANISH = {
    "afghaner": "Afghanistan",
    "afghanere": "Afghanistan",
    "afghansk": "Afghanistan",
    "afghanistan": "Afghanistan",
    "albaner": "Albania",
    "albanere": "Albania",
    "albansk": "Albania",
    "albanien": "Albania",
    "algerier": "Algeria",
    "algeriere": "Algeria",
    "algerisk": "Algeria",
    "algeriet": "Algeria",
    "amerikaner": "United States of America",
    "amerikanere": "United States of America",
    "amerikansk": "United States of America",
    "amerikas forenede stater": "United States of America",
    "andorra": "Andorra",
    "andorraner": "Andorra",
    "andorransk": "Andorra",
    "angola": "Angola",
    "angolaner": "Angola",
    "angolansk": "Angola",
    "antarktis": "Antarctica",
    "antigua og barbuda": "Antigua and Barbuda",
    "argentina": "Argentina",
    "argentiner": "Argentina",
    "argentinere": "Argentina",
    "argentinsk": "Argentina",
    "armenien": "Armenia",
    "armenier": "Armenia",
    "armeniere": "Armenia",
    "armensk": "Armenia",
    "aserbajdsjan": "Azerbaijan",
    "aserbajdsjaner": "Azerbaijan",
    "aserbajdsjansk": "Azerbaijan",
    "australien": "Australia",
    "australier": "Australia",
    "australiere": "Australia",
    "australsk": "Australia",
    "bahamas": "The Bahamas",
    "bahrain": "Bahrain",
    "bahrainer": "Bahrain",
    "bahrainsk": "Bahrain",
    "bangladesh": "Bangladesh",
    "bangladesher": "Bangladesh",
    "bangladeshisk": "Bangladesh",
    "barbados": "Barbados",
    "barbadier": "Barbados",
    "barbadisk": "Barbados",
    "belgien": "Belgium",
    "belgier": "Belgium",
    "belgiere": "Belgium",
    "belgisk": "Belgium",
    "belize": "Belize",
    "belizer": "Belize",
    "belizisk": "Belize",
    "benin": "Benin",
    "beniner": "Benin",
    "beninsk": "Benin",
    "bhutan": "Bhutan",
    "bhutaner": "Bhutan",
    "bhutansk": "Bhutan",
    "bolivia": "Bolivia",
    "bolivianer": "Bolivia",
    "boliviansk": "Bolivia",
    "bosnien-hercegovina": "Bosnia and Herzegovina",
    "bosnier": "Bosnia and Herzegovina",
    "bosniere": "Bosnia and Herzegovina",
    "bosnisk": "Bosnia and Herzegovina",
    "botswana": "Botswana",
    "botswaner": "Botswana",
    "botswansk": "Botswana",
    "brasilien": "Brazil",
    "brasilianer": "Brazil",
    "brasilianere": "Brazil",
    "brasiliansk": "Brazil",
    "brite": "United Kingdom",
    "briter": "United Kingdom",
    "britisk": "United Kingdom",
    "brunei": "Brunei",
    "bruneier": "Brunei",
    "bruneisk": "Brunei",
    "bulgarien": "Bulgaria",
    "bulgarer": "Bulgaria",
    "bulgarere": "Bulgaria",
    "bulgarsk": "Bulgaria",
    "burkina faso": "Burkina Faso",
    "burkiner": "Burkina Faso",
    "burkinsk": "Burkina Faso",
    "burma": "Myanmar",
    "burundi": "Burundi",
    "burundier": "Burundi",
    "burundisk": "Burundi",
    "cambodja": "Cambodia",
    "cambodjaner": "Cambodia",
    "cambodjansk": "Cambodia",
    "cameroun": "Cameroon",
    "camerouner": "Cameroon",
    "camerounsk": "Cameroon",
    "canada": "Canada",
    "canadier": "Canada",
    "canadiere": "Canada",
    "canadisk": "Canada",
    "centralafrikanske republik": "Central African Republic",
    "chile": "Chile",
    "chilener": "Chile",
    "chilenere": "Chile",
    "chilensk": "Chile",
    "colombia": "Colombia",
    "colombianer": "Colombia",
    "colombiansk": "Colombia",
    "comorerne": "Comoros",
    "congo-brazzaville": "Republic of the Congo",
    "costa rica": "Costa Rica",
    "costaricaner": "Costa Rica",
    "costaricansk": "Costa Rica",
    "cuba": "Cuba",
    "cubaner": "Cuba",
    "cubanere": "Cuba",
    "cubansk": "Cuba",
    "cypern": "Cyprus",
    "cypriot": "Cyprus",
    "cyprioter": "Cyprus",
    "cypriotisk": "Cyprus",
    "danmark": "Denmark",
    "dansk": "Denmark",
    "dansker": "Denmark",
    "danskere": "Denmark",
    "demokratiske republik congo": "Democratic Republic of the Congo",
    "djibouti": "Djibouti",
    "dominica": "Dominica",
    "dominikanske republik": "Dominican Republic",
    "dr congo": "Democratic Republic of the Congo",
    "ecuador": "Ecuador",
    "ecuadorianer": "Ecuador",
    "ecuadoriansk": "Ecuador",
    "egypten": "Egypt",
    "egypter": "Egypt",
    "egyptisk": "Egypt",
    "el salvador": "El Salvador",
    "elfenbenskysten": "Ivory Coast",
    "eritrea": "Eritrea",
    "eritreer": "Eritrea",
    "eritreere": "Eritrea",
    "eritreisk": "Eritrea",
    "eswatini": "eSwatini",
    "estland": "Estonia",
    "ester": "Estonia",
    "estere": "Estonia",
    "estisk": "Estonia",
    "etiopien": "Ethiopia",
    "etiopier": "Ethiopia",
    "etiopiere": "Ethiopia",
    "etiopisk": "Ethiopia",
    "fiji": "Fiji",
    "filippiner": "Philippines",
    "filippinere": "Philippines",
    "filippinerne": "Philippines",
    "filippinsk": "Philippines",
    "finland": "Finland",
    "finne": "Finland",
    "finner": "Finland",
    "finsk": "Finland",
    "forenede arabiske emirater": "United Arab Emirates",
    "frankrig": "France",
    "fransk": "France",
    "franskmand": "France",
    "franskmænd": "France",
    "gabon": "Gabon",
    "gambia": "Gambia",
    "georgien": "Georgia",
    "ghana": "Ghana",
    "grenada": "Grenada",
    "grækenland": "Greece",
    "græker": "Greece",
    "grækere": "Greece",
    "græsk": "Greece",
    "guatemala": "Guatemala",
    "guinea": "Guinea",
    "guinea-bissau": "Guinea-Bissau",
    "guyana": "Guyana",
    "haiti": "Haiti",
    "holland": "Netherlands",
    "hollandsk": "Netherlands",
    "hollænder": "Netherlands",
    "hollændere": "Netherlands",
    "honduras": "Honduras",
    "hviderusland": "Belarus",
    "hviderusser": "Belarus",
    "hviderussere": "Belarus",
    "hviderussisk": "Belarus",
    "indien": "India",
    "inder": "India",
    "indere": "India",
    "indisk": "India",
    "indonesien": "Indonesia",
    "irak": "Iraq",
    "iraker": "Iraq",
    "irakere": "Iraq",
    "irakisk": "Iraq",
    "iran": "Iran",
    "iraner": "Iran",
    "iranere": "Iran",
    "iransk": "Iran",
    "irland": "Ireland",
    "irer": "Ireland",
    "irere": "Ireland",
    "irsk": "Ireland",
    "island": "Iceland",
    "islandsk": "Iceland",
    "islænding": "Iceland",
    "islændinge": "Iceland",
    "israel": "Israel",
    "israeler": "Israel",
    "israelere": "Israel",
    "israelsk": "Israel",
    "italien": "Italy",
    "italiener": "Italy",
    "italienere": "Italy",
    "italiensk": "Italy",
    "jamaica": "Jamaica",
    "japan": "Japan",
    "japaner": "Japan",
    "japanere": "Japan",
    "japansk": "Japan",
    "jordan": "Jordan",
    "jordaner": "Jordan",
    "jordanere": "Jordan",
    "jordansk": "Jordan",
    "kap verde": "Cabo Verde",
    "kapverdianer": "Cabo Verde",
    "kapverdisk": "Cabo Verde",
    "kasakhstan": "Kazakhstan",
    "kashmir": "Kashmir",
    "kenya": "Kenya",
    "kina": "China",
    "kineser": "China",
    "kinesere": "China",
    "kinesisk": "China",
    "kirgisistan": "Kyrgyzstan",
    "kiribati": "Kiribati",
    "kosovo": "Kosovo",
    "kroat": "Croatia",
    "kroater": "Croatia",
    "kroatien": "Croatia",
    "kroatisk": "Croatia",
    "kuwait": "Kuwait",
    "laos": "Laos",
    "lesotho": "Lesotho",
    "letland": "Latvia",
    "letter": "Latvia",
    "lettere": "Latvia",
    "lettisk": "Latvia",
    "libanon": "Lebanon",
    "liberia": "Liberia",
    "libyen": "Libya",
    "liechtenstein": "Liechtenstein",
    "litauen": "Lithuania",
    "litauer": "Lithuania",
    "litauere": "Lithuania",
    "litauisk": "Lithuania",
    "luxembourg": "Luxembourg",
    "madagaskar": "Madagascar",
    "malawi": "Malawi",
    "malaysia": "Malaysia",
    "maldiverne": "Maldives",
    "mali": "Mali",
    "malta": "Malta",
    "marokkaner": "Morocco",
    "marokkanere": "Morocco",
    "marokkansk": "Morocco",
    "marokko": "Morocco",
    "marshalløerne": "Marshall Islands",
    "mauretanien": "Mauritania",
    "mauritius": "Mauritius",
    "mexicaner": "Mexico",
    "mexicanere": "Mexico",
    "mexicansk": "Mexico",
    "mexico": "Mexico",
    "mikronesiens forenede stater": "Federated States of Micronesia",
    "moldova": "Moldova",
    "monaco": "Monaco",
    "mongoliet": "Mongolia",
    "montenegro": "Montenegro",
    "mozambique": "Mozambique",
    "myanmar": "Myanmar",
    "namibia": "Namibia",
    "nauru": "Nauru",
    "nederlandene": "Netherlands",
    "nederlandsk": "Netherlands",
    "nederlænder": "Netherlands",
    "nepal": "Nepal",
    "new zealand": "New Zealand",
    "nicaragua": "Nicaragua",
    "niger": "Niger",
    "nigeria": "Nigeria",
    "nordcypern": "Northern Cyprus",
    "nordkorea": "North Korea",
    "nordkoreaner": "North Korea",
    "nordkoreansk": "North Korea",
    "nordmakedonien": "North Macedonia",
    "nordmand": "Norway",
    "nordmænd": "Norway",
    "norge": "Norway",
    "norsk": "Norway",
    "oman": "Oman",
    "pakistan": "Pakistan",
    "pakistaner": "Pakistan",
    "pakistanere": "Pakistan",
    "pakistansk": "Pakistan",
    "palau": "Palau",
    "panama": "Panama",
    "papua ny guinea": "Papua New Guinea",
    "paraguay": "Paraguay",
    "peru": "Peru",
    "peruaner": "Peru",
    "peruansk": "Peru",
    "polak": "Poland",
    "polakker": "Poland",
    "polen": "Poland",
    "polsk": "Poland",
    "portugal": "Portugal",
    "portugiser": "Portugal",
    "portugisere": "Portugal",
    "portugisisk": "Portugal",
    "qatar": "Qatar",
    "republikken congo": "Republic of the Congo",
    "rumæner": "Romania",
    "rumænere": "Romania",
    "rumænsk": "Romania",
    "rumænien": "Romania",
    "rusland": "Russia",
    "russer": "Russia",
    "russere": "Russia",
    "russisk": "Russia",
    "rwanda": "Rwanda",
    "saint kitts og nevis": "Saint Kitts and Nevis",
    "saint lucia": "Saint Lucia",
    "saint vincent og grenadinerne": "Saint Vincent and the Grenadines",
    "salomonøerne": "Solomon Islands",
    "salvadoraner": "El Salvador",
    "salvadoransk": "El Salvador",
    "samoa": "Samoa",
    "san marino": "San Marino",
    "são tomé og príncipe": "São Tomé and Principe",
    "saudi-arabien": "Saudi Arabia",
    "saudiaraber": "Saudi Arabia",
    "saudiarabisk": "Saudi Arabia",
    "schweiz": "Switzerland",
    "schweizer": "Switzerland",
    "schweizere": "Switzerland",
    "schweizisk": "Switzerland",
    "senegal": "Senegal",
    "serber": "Republic of Serbia",
    "serbere": "Republic of Serbia",
    "serbien": "Republic of Serbia",
    "serbisk": "Republic of Serbia",
    "seychellerne": "Seychelles",
    "sierra leone": "Sierra Leone",
    "singapore": "Singapore",
    "slovak": "Slovakia",
    "slovakiet": "Slovakia",
    "slovakisk": "Slovakia",
    "slovakker": "Slovakia",
    "slovener": "Slovenia",
    "slovenere": "Slovenia",
    "slovenien": "Slovenia",
    "slovensk": "Slovenia",
    "somalia": "Somalia",
    "somaliland": "Somaliland",
    "spanien": "Spain",
    "spanier": "Spain",
    "spaniere": "Spain",
    "spansk": "Spain",
    "sri lanka": "Sri Lanka",
    "storbritannien": "United Kingdom",
    "sudan": "Sudan",
    "surinam": "Suriname",
    "svensk": "Sweden",
    "svensker": "Sweden",
    "svenskere": "Sweden",
    "sverige": "Sweden",
    "swaziland": "eSwatini",
    "sydafrikaner": "South Africa",
    "sydafrikansk": "South Africa",
    "sydafrika": "South Africa",
    "sydkorea": "South Korea",
    "sydkoreaner": "South Korea",
    "sydkoreansk": "South Korea",
    "sydsudan": "South Sudan",
    "syrien": "Syria",
    "syrer": "Syria",
    "syrere": "Syria",
    "syrisk": "Syria",
    "tadsjikistan": "Tajikistan",
    "taiwan": "Taiwan",
    "tanzania": "United Republic of Tanzania",
    "tchad": "Chad",
    "tchader": "Chad",
    "tchadisk": "Chad",
    "thailand": "Thailand",
    "thailandsk": "Thailand",
    "thailænder": "Thailand",
    "thailændere": "Thailand",
    "tjekke": "Czechia",
    "tjekker": "Czechia",
    "tjekkiet": "Czechia",
    "tjekkisk": "Czechia",
    "togo": "Togo",
    "tonga": "Tonga",
    "trinidad og tobago": "Trinidad and Tobago",
    "tunesien": "Tunisia",
    "turkmenistan": "Turkmenistan",
    "tuvalu": "Tuvalu",
    "tyrker": "Turkey",
    "tyrkere": "Turkey",
    "tyrket": "Turkey",
    "tyrkisk": "Turkey",
    "tysk": "Germany",
    "tysker": "Germany",
    "tyskere": "Germany",
    "tyskland": "Germany",
    "uganda": "Uganda",
    "uk": "United Kingdom",
    "ukraine": "Ukraine",
    "ukrainer": "Ukraine",
    "ukrainere": "Ukraine",
    "ukrainsk": "Ukraine",
    "ungarer": "Hungary",
    "ungarere": "Hungary",
    "ungarn": "Hungary",
    "ungarsk": "Hungary",
    "uruguay": "Uruguay",
    "usa": "United States of America",
    "usbekistan": "Uzbekistan",
    "vanuatu": "Vanuatu",
    "vatikanstaten": "Vatican",
    "venezuela": "Venezuela",
    "vestsahara": "Western Sahara",
    "vietnam": "Vietnam",
    "vietnameser": "Vietnam",
    "vietnamesere": "Vietnam",
    "vietnamesisk": "Vietnam",
    "yemen": "Yemen",
    "zambia": "Zambia",
    "zimbabwe": "Zimbabwe",
    "ægypten": "Egypt",
    "ægypter": "Egypt",
    "ægyptisk": "Egypt",
    "ækvatorialguinea": "Equatorial Guinea",
    "østtimor": "East Timor",
    "østrig": "Austria",
    "østriger": "Austria",
    "østrigere": "Austria",
    "østrigsk": "Austria",
}


